# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 4.1

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /opt/homebrew/bin/cmake

# The command to remove a file.
RM = /opt/homebrew/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/Users/eliasbajotangeloski/Desktop/Enseirb - Matmeca /Cours/2A/TP_C/Projet_WindKessel"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/Users/eliasbajotangeloski/Desktop/Enseirb - Matmeca /Cours/2A/TP_C/Projet_WindKessel"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake cache editor..."
	/opt/homebrew/bin/ccmake -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/opt/homebrew/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/eliasbajotangeloski/Desktop/Enseirb - Matmeca /Cours/2A/TP_C/Projet_WindKessel/CMakeFiles" "/Users/eliasbajotangeloski/Desktop/Enseirb - Matmeca /Cours/2A/TP_C/Projet_WindKessel//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/Users/eliasbajotangeloski/Desktop/Enseirb - Matmeca /Cours/2A/TP_C/Projet_WindKessel/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named DM_ode_Release

# Build rule for target.
DM_ode_Release: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 DM_ode_Release
.PHONY : DM_ode_Release

# fast build rule for target.
DM_ode_Release/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/build
.PHONY : DM_ode_Release/fast

SRC/OdeSolver.o: SRC/OdeSolver.cpp.o
.PHONY : SRC/OdeSolver.o

# target to build an object file
SRC/OdeSolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/OdeSolver.cpp.o
.PHONY : SRC/OdeSolver.cpp.o

SRC/OdeSolver.i: SRC/OdeSolver.cpp.i
.PHONY : SRC/OdeSolver.i

# target to preprocess a source file
SRC/OdeSolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/OdeSolver.cpp.i
.PHONY : SRC/OdeSolver.cpp.i

SRC/OdeSolver.s: SRC/OdeSolver.cpp.s
.PHONY : SRC/OdeSolver.s

# target to generate assembly for a file
SRC/OdeSolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/OdeSolver.cpp.s
.PHONY : SRC/OdeSolver.cpp.s

SRC/P_Q_System.o: SRC/P_Q_System.cpp.o
.PHONY : SRC/P_Q_System.o

# target to build an object file
SRC/P_Q_System.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/P_Q_System.cpp.o
.PHONY : SRC/P_Q_System.cpp.o

SRC/P_Q_System.i: SRC/P_Q_System.cpp.i
.PHONY : SRC/P_Q_System.i

# target to preprocess a source file
SRC/P_Q_System.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/P_Q_System.cpp.i
.PHONY : SRC/P_Q_System.cpp.i

SRC/P_Q_System.s: SRC/P_Q_System.cpp.s
.PHONY : SRC/P_Q_System.s

# target to generate assembly for a file
SRC/P_Q_System.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/P_Q_System.cpp.s
.PHONY : SRC/P_Q_System.cpp.s

SRC/PdeSolver.o: SRC/PdeSolver.cpp.o
.PHONY : SRC/PdeSolver.o

# target to build an object file
SRC/PdeSolver.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/PdeSolver.cpp.o
.PHONY : SRC/PdeSolver.cpp.o

SRC/PdeSolver.i: SRC/PdeSolver.cpp.i
.PHONY : SRC/PdeSolver.i

# target to preprocess a source file
SRC/PdeSolver.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/PdeSolver.cpp.i
.PHONY : SRC/PdeSolver.cpp.i

SRC/PdeSolver.s: SRC/PdeSolver.cpp.s
.PHONY : SRC/PdeSolver.s

# target to generate assembly for a file
SRC/PdeSolver.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/PdeSolver.cpp.s
.PHONY : SRC/PdeSolver.cpp.s

SRC/coupling.o: SRC/coupling.cpp.o
.PHONY : SRC/coupling.o

# target to build an object file
SRC/coupling.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/coupling.cpp.o
.PHONY : SRC/coupling.cpp.o

SRC/coupling.i: SRC/coupling.cpp.i
.PHONY : SRC/coupling.i

# target to preprocess a source file
SRC/coupling.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/coupling.cpp.i
.PHONY : SRC/coupling.cpp.i

SRC/coupling.s: SRC/coupling.cpp.s
.PHONY : SRC/coupling.s

# target to generate assembly for a file
SRC/coupling.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/coupling.cpp.s
.PHONY : SRC/coupling.cpp.s

SRC/main.o: SRC/main.cpp.o
.PHONY : SRC/main.o

# target to build an object file
SRC/main.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/main.cpp.o
.PHONY : SRC/main.cpp.o

SRC/main.i: SRC/main.cpp.i
.PHONY : SRC/main.i

# target to preprocess a source file
SRC/main.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/main.cpp.i
.PHONY : SRC/main.cpp.i

SRC/main.s: SRC/main.cpp.s
.PHONY : SRC/main.s

# target to generate assembly for a file
SRC/main.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/main.cpp.s
.PHONY : SRC/main.cpp.s

SRC/utils.o: SRC/utils.cpp.o
.PHONY : SRC/utils.o

# target to build an object file
SRC/utils.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/utils.cpp.o
.PHONY : SRC/utils.cpp.o

SRC/utils.i: SRC/utils.cpp.i
.PHONY : SRC/utils.i

# target to preprocess a source file
SRC/utils.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/utils.cpp.i
.PHONY : SRC/utils.cpp.i

SRC/utils.s: SRC/utils.cpp.s
.PHONY : SRC/utils.s

# target to generate assembly for a file
SRC/utils.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/utils.cpp.s
.PHONY : SRC/utils.cpp.s

SRC/windkessel.o: SRC/windkessel.cpp.o
.PHONY : SRC/windkessel.o

# target to build an object file
SRC/windkessel.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/windkessel.cpp.o
.PHONY : SRC/windkessel.cpp.o

SRC/windkessel.i: SRC/windkessel.cpp.i
.PHONY : SRC/windkessel.i

# target to preprocess a source file
SRC/windkessel.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/windkessel.cpp.i
.PHONY : SRC/windkessel.cpp.i

SRC/windkessel.s: SRC/windkessel.cpp.s
.PHONY : SRC/windkessel.s

# target to generate assembly for a file
SRC/windkessel.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/DM_ode_Release.dir/build.make CMakeFiles/DM_ode_Release.dir/SRC/windkessel.cpp.s
.PHONY : SRC/windkessel.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... DM_ode_Release"
	@echo "... SRC/OdeSolver.o"
	@echo "... SRC/OdeSolver.i"
	@echo "... SRC/OdeSolver.s"
	@echo "... SRC/P_Q_System.o"
	@echo "... SRC/P_Q_System.i"
	@echo "... SRC/P_Q_System.s"
	@echo "... SRC/PdeSolver.o"
	@echo "... SRC/PdeSolver.i"
	@echo "... SRC/PdeSolver.s"
	@echo "... SRC/coupling.o"
	@echo "... SRC/coupling.i"
	@echo "... SRC/coupling.s"
	@echo "... SRC/main.o"
	@echo "... SRC/main.i"
	@echo "... SRC/main.s"
	@echo "... SRC/utils.o"
	@echo "... SRC/utils.i"
	@echo "... SRC/utils.s"
	@echo "... SRC/windkessel.o"
	@echo "... SRC/windkessel.i"
	@echo "... SRC/windkessel.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

